#!/bin/bash
# To update GPFS we need to kick everyone off of the node and then restart GPFS
# There will be a 1 hour count down before all user procceses are killed 

count_down=36
step=6
while [ ${count_down} -gt 0 ] ; do
    echo "This system will do down for updates in ${count_down} seconds, please save all work and logout. All users will be disconnected during the update."
    sleep ${step}
    count_down=$(( count_down - step ))
done
#Kill user processes
for user in $(who -q | head -1 | sort -u | grep -v root); do 
    echo "pkill -u ${user}"; 
done

#echo "System is currently being updated. Please try again in a few minutes" > /etc/nologin

#Connections to RDS will need to be off for Kernal updates
/usr/lpp/mmfs/bin/mmshutdown

#Run updates respecting the settings in automatic.conf
/usr/bin/dnf-automatic /etc/dnf/automatic.conf

#Rebuild portability layer. It is easier to just assume this needs doing
/usr/lpp/mmfs/bin/mmbuildgpl

#Startup GPFS which should auto mount RDS
/usr/lpp/mmfs/bin/mmstartup

#Give GPFS a moment to finish arbitration
sleep 60

#Only let the users back in if RDS has been able to mount user home directories
if [[ $(systemctl check gpfs) == "active" ]] ; then 
    if [[ -d /rds/general/user ]] ; then 
        echo "beep"; 
    fi
fi
